version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.19.0
  - dependency-name: rollup
    versions:
    - 2.38.3
