version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.14.0
    steps:
      - run:
          name: yarn
          command: curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
      - checkout
      - run:
          name: install
          command: $HOME/.yarn/bin/yarn --frozen-lockfile
      - run:
          name: test
          command: $HOME/.yarn/bin/yarn test
